id: PF222ABD1
initial_creation_type: input
source_metadata:
  title: TYKYN
  language: zh
  volumes:
    85b07993ed0e4dc085ab61043d39ce80:
      title: Complete text
      base_file: Complete text.txt
      work_id: W34E45B67
  chapter_to_tile: {}
created_at: '2022-03-02T09:14:35.836737'
last_modified_at: '2022-03-02T09:14:35.836757'
